# Nome do Workflow
name: CI com Testes e Comentário de Coverage

# Gatilhos (Triggers)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Definição dos Jobs
jobs:
  build-test-comment:
    # Ambiente de execução
    runs-on: ubuntu-latest

    # Permissão para a action poder comentar no PR
    permissions:
      pull-requests: write

    # Passos do Job
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Rodar testes e gerar dados de coverage
        run: npm run coverage

      - name: Garantir que a pasta de coverage exista
        run: mkdir -p ./coverage

      - name: Gerar arquivo de sumário para o comentário do PR
        run: npm run coverage:summary > ./coverage/coverage-summary.txt

      # --- PASSO CORRIGIDO PARA FORMATAÇÃO CORRETA ---
      - name: Preparar corpo do comentário
        id: coverage_comment
        run: |
          echo 'body<<EOF' >> $GITHUB_OUTPUT
          echo '### :white_check_mark: Resumo do Coverage' >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          cat ./coverage/coverage-summary.txt >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Publicar comentário de coverage no PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage_comment.outputs.body }}
